---
title: "Trabalho Final - Boruta"
output: html_notebook
---
Carregando os pacotes necessários:

```{r}
library(Boruta)
```

Após rodar o Compilado.Rmd sem Dummys
Lendo o .csv e splitando os dados em treino e test

```{r}
data <- subset(read.csv2(file="drug_use_data.csv"), select = -c(X, ID, Country, Ethnicity))
```

Preparando os datasets para cada droga:

```{r}
data_alcohol <- subset(data, select = -c(ecstasy_user, cannabis_user, stimulating_user))
data_cannabis <- subset(data, select = -c(alcohol_user, ecstasy_user, stimulating_user))
data_ecstasy <- subset(data, select = -c(alcohol_user, cannabis_user, stimulating_user))
data_stimulating <- subset(data, select = -c(alcohol_user, ecstasy_user, cannabis_user))
```

Calculando Variable Importance pelo Método Boruta:

```{r}
boruta_alcohol <- Boruta(alcohol_user ~ ., data = data_alcohol, doTrace=2)
boruta_alcohol_sig <- names(boruta_alcohol$finalDecision[boruta_alcohol$finalDecision %in% c("Confirmed", "Tentative")])
print(boruta_alcohol_sig)
plot(boruta_alcohol, cex.axis=.7, las=2, xlab="", main="Alcohol Variable Importance")

boruta_cannabis <- Boruta(cannabis_user ~ ., data = data_cannabis, doTrace=2)
boruta_cannabis_sig <- names(boruta_cannabis$finalDecision[boruta_cannabis$finalDecision %in% c("Confirmed", "Tentative")])
print(boruta_cannabis_sig)
plot(boruta_cannabis, cex.axis=.7, las=2, xlab="", main="Cannabis Variable Importance")

boruta_ecstasy <- Boruta(ecstasy_user ~ ., data = data_ecstasy, doTrace=2)
boruta_ecstasy_sig <- names(boruta_ecstasy$finalDecision[boruta_ecstasy$finalDecision %in% c("Confirmed", "Tentative")])
print(boruta_ecstasy_sig)
plot(boruta_ecstasy, cex.axis=.7, las=2, xlab="", main="Ecstasy Variable Importance")

boruta_stimulating <- Boruta(stimulating_user ~ ., data = data_stimulating, doTrace=2)
boruta_stimulating_sig <- names(boruta_stimulating$finalDecision[boruta_stimulating$finalDecision %in% c("Confirmed", "Tentative")])
print(boruta_stimulating_sig)
plot(boruta_stimulating, cex.axis=.7, las=2, xlab="", main="Stimulants Variable Importance")
```