----
title: "Trabalho Final - Regressao Logistica"
output: html_notebook
---

## Cannabis

-> primeiro rodar os chunks do Compilado

Colocando os dados em variaveis especificas para o experimento:

```{r}
dataLogCannabis <- data
dataLogCannabis$Age <- as.factor(dataLogCannabis$Age)
dataLogCannabis$Gender <- as.factor(dataLogCannabis$Gender)
dataLogCannabis$Education <- as.factor(dataLogCannabis$Education)
dataLogCannabis$NScore <- as.factor(dataLogCannabis$NScore)
dataLogCannabis$EScore <- as.factor(dataLogCannabis$EScore)
dataLogCannabis$AScore <- as.factor(dataLogCannabis$AScore)
dataLogCannabis$CScore <- as.factor(dataLogCannabis$CScore)
dataLogCannabis$OScore <- as.factor(dataLogCannabis$OScore)
dataLogCannabis$cannabis_user <- as.factor(dataLogCannabis$cannabis_user)
head(dataLogCannabis)

```

Separar em treino e teste usando o create data partition que garante distribuicoes similares:

```{r}
set.seed(205650)
indexes <- createDataPartition(dataLogCannabis$cannabis_user, p = 0.85, list = FALSE)
trainLogCannabis = dataLogCannabis[indexes, ]
testLogCannabis = dataLogCannabis[-indexes, ]
```

```{r}
table(trainLogCannabis$cannabis_user)
table(dataLogCannabis$cannabis_user)
```


Rodando o glm full model:
```{r}
trainLogCannabis <- subset(trainLogCannabis, select = -c(ID, alcohol_user, ecstasy_user, stimulating_user))


fullModLogCannabis <- glm(cannabis_user ~ ., data=trainLogCannabis, family = "binomial")


predFullCannabis <- ifelse(predict(fullModLogCannabis, newdata = testLogCannabis) >= 0.5, 1, 0)
confusionMatrix(table(predFullCannabis, testLogCannabis$cannabis_user))

```

StepAIC:

```{r}
stepCannabis <- stepAIC(fullModLogCannabis, direction = "both")
stepCannabis$anova
predStepCannabis <- ifelse(predict(stepCannabis, newdata = testLogCannabis) >= 0.5, 1, 0)
confusionMatrix(table(predStepCannabis, testLogCannabis$cannabis_user))
```

Ponto de corte em 0.8:
```{r}
predStepCannabis <- ifelse(predict(stepCannabis, newdata = testLogCannabis) >= 0.8, 1, 0)
confusionMatrix(table(predStepCannabis, testLogCannabis$cannabis_user))

```


Importancia das variaveis: 
```{r}
variableImportance <- varImp(fullModLogCannabis , scale = FALSE)
variableImportance
```

Plotting:
```{r}
library(ggplot2)
## now we can plot the data
predicted.data <- data.frame(
  prob.user=stepCannabis$fitted.values,
  user=trainLogCannabis$cannabis_user)
 
predicted.data <- predicted.data[
  order(predicted.data$prob.user, decreasing=FALSE),]
predicted.data$rank <- 1:nrow(predicted.data)
 
## Lastly, we can plot the predicted probabilities for each sample having
## heart disease and color by whether or not they actually had heart disease
ggplot(data=predicted.data, aes(x=rank, y=prob.user)) +
  geom_point(aes(color=user), alpha=1, shape=4, stroke=2) +
  xlab("Index") +
  ylab("Predicted probability of being a Cannabis user")
```



## Referencias
http://www.sthda.com/english/articles/36-classification-methods-essentials/150-stepwise-logistic-regression-essentials-in-r/
http://www.utstat.toronto.edu/~brunner/oldclass/appliedf11/handouts/2101f11StepwiseLogisticR.pdf
https://machinelearningmastery.com/how-to-estimate-model-accuracy-in-r-using-the-caret-package/
