# This dataset consists of data on 32 models of car, taken from an American motoring magazine (1974 Motor Trend magazine). For each car, you have 11 features, expressed in varying units (US units), They are as follows:
#   
# mpg: Fuel consumption (Miles per (US) gallon): more powerful and heavier cars tend to consume more fuel.
# 
# cyl: Number of cylinders: more powerful cars often have more cylinders
# 
# disp: Displacement (cu.in.): the combined volume of the engine's cylinders
# 
# hp: Gross horsepower: this is a measure of the power generated by the car
# 
# drat: Rear axle ratio: this describes how a turn of the drive shaft corresponds to a turn of the wheels. Higher values will decrease fuel efficiency.
# 
# wt: Weight (1000 lbs): pretty self-explanatory!
# 
# qsec: 1/4 mile time: the cars speed and acceleration
# 
# vs: Engine block: this denotes whether the vehicle's engine is shaped like a "V", or is a more common straight shape.
# 
# am: Transmission: this denotes whether the car's transmission is automatic (0) or manual (1).
# 
# gear: Number of forward gears: sports cars tend to have more gears.
# 
# carb: Number of carburetors: associated with more powerful engines
# 
# Note that the units used vary and occupy different scales.

attach(mtcars)


# vari?veis am e vs s?o categ?ricas e devem ser exclu?das
names(mtcars)
dados=mtcars[,-c(8,9)]
head(dados)


mtcars.pca <- prcomp(dados, center = TRUE,scale. = TRUE)
summary(mtcars.pca)

# Componentes 1 e 2 explicam 0.62+0.23 % da variabilidade!!

# Checando...
DD = svd(as.matrix(scale(dados, center=TRUE)))
round(DD$v,2)
round(mtcars.pca$rotation,2)



# plotando f?cil e bonito!
library(devtools)
install_github("vqv/ggbiplot")

library(ggbiplot)


ggbiplot(mtcars.pca)+theme_minimal() 
# cada ponto é o carro plotado no plano novo criado pelo PCA
# aqui estamos usando PCA1 e PCA2 que sao as componentes que explicam a maioria da variabilidade
# cada vetor é uma variavel 
ggbiplot(mtcars.pca, labels=rownames(mtcars))+theme_minimal()


# Analisando a origem dos carros talvez possamos enxergar alguma estrutura nova?

mtcars.country <- c(rep("Japan", 3), rep("US",4), rep("Europe", 7),rep("US",3), "Europe", rep("Japan", 3), rep("US",4), rep("Europe", 3), "US", rep("Europe", 3))

#Elipses criadas a partir da normal multivariada
ggbiplot(mtcars.pca, labels=rownames(mtcars), groups=mtcars.country)+ theme_minimal() 
ggbiplot(mtcars.pca, ellipse=TRUE, labels=rownames(mtcars), groups=mtcars.country)+ theme_minimal() 

?ggbiplot


ggbiplot(mtcars.pca, obs.scale = 1, var.scale = 1,var.axes=FALSE,   labels=rownames(mtcars), groups=mtcars.country)


# pobre das outras componentes! N?o vamos olhar para elas?

ggbiplot(mtcars.pca, choices=c(3,4), ellipse=TRUE,  labels=rownames(mtcars), groups=mtcars.country)+ theme_minimal() 


########################
##
##   K-means
##
########################


km = kmeans(dados[,c("hp","mpg")],2)

pchs=(mtcars.country=="Japan")*1  +(mtcars.country=="Europe")*22  +(mtcars.country=="US")*24
cores = ifelse(km$cluster==1,"blue","red")

plot(dados[,c("hp","mpg")], 
     col=cores, 
     pch=pchs,
     cex=2)
legend("topright",legend=c("Jap?o","Europa", "EUA"), pch=c(1,22,24), bty="n" )
points(km$centers, pch=18, cex=2)


# Condi??o inicial

centros.ini=rbind(c(50,20),c(300,30))
pchs=(mtcars.country=="Japan")*1  +(mtcars.country=="Europe")*22  +(mtcars.country=="US")*24

plot(dados[,c("hp","mpg")], pch=pchs,cex=2)

legend("topright",legend=c("Jap?o","Europa", "EUA"), pch=c(1,22,24), bty="n" )
points(centros.ini, pch="0")

#Primeira itera??o

km1 = kmeans( dados[,c("hp","mpg")],2, iter.max = 1, centers = centros.ini)
cores = ifelse(km1$cluster==1,"blue","red")

plot(dados[,c("hp","mpg")], 
     col=cores, 
     pch=pchs,
     cex=2)

legend("topright",legend=c("Jap?o","Europa", "EUA"), pch=c(1,22,24), bty="n" )
points(centros.ini, pch="0")
points(km1$centers, pch="1")


#Segunda itera??o

km2 = kmeans( dados[,c("hp","mpg")],2, iter.max = 2, centers = centros.ini)
cores = ifelse(km2$cluster==1,"blue","red")

plot(dados[,c("hp","mpg")], 
     col=cores, 
     pch=pchs,
     cex=2)

legend("topright",legend=c("Jap?o","Europa", "EUA"), pch=c(1,22,24), bty="n" )
points(centros.ini, pch="0")
points(km1$centers, pch="1")
points(km2$centers, pch="2")

#######
#
# K-means na dimens?o do PCH
#
#######

plot(mtcars.pca$x,pch=pchs,cex=2)

km.pca = kmeans(mtcars.pca$x,2)

cores = ifelse(km.pca$cluster==1,"blue","red")

plot(mtcars.pca$x, 
     col=cores, 
     pch=pchs,
     cex=2)

legend(x=-4 ,y=5, ncol=3,legend=c("Jap?o","Europa", "EUA"), pch=c(1,22,24), bty="n", cex=1.2 )

points(km.pca$centers, pch=18, cex=2)

